CREATE TABLE IF NOT EXISTS dim_roles (
    id TINYINT NOT NULL AUTO_INCREMENT,
    role_name VARCHAR(255) NOT NULL,
    processing_floor TINYINT,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);