CREATE TABLE IF NOT EXISTS ft_daily_customer_sales_ts (
    start_of_month_date DATE NOT NULL,
    as_of_date DATE NOT NULL,
    customer_group_name VARCHAR(255) NOT NULL,
    customer_code VARCHAR(25) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    zipcode VARCHAR(255),
    industry VARCHAR(100),
    trade_ind VARCHAR(25) NOT NULL,
    is_active VARCHAR(1) NOT NULL,
    payment_terms VARCHAR(50) NOT NULL,
    sales_employee VARCHAR(255) NOT NULL,
    first_sales_date DATE,
    latest_sales_date DATE,
    relationship_length VARCHAR(100),
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(255) NOT NULL,
    sales_price NUMERIC(10,2) NOT NULL,
    sales_qty NUMERIC(10,2) NOT NULL,
    revenue NUMERIC(10,2) NOT NULL,
    profit NUMERIC(10,2) NOT NULL,
    pc1 NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (as_of_date, pdt_code, customer_group_name, customer_code)
);