CREATE TABLE IF NOT EXISTS ft_purchases_alerts (
    doc_date DATE NOT NULL,
    doc_num VARCHAR(50) NOT NULL,
    line_num SMALLINT NOT NULL,
    supplier_code VARCHAR(25) NOT NULL,
    supplier_name VARCHAR(100) NOT NULL,
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(100) NOT NULL,
    uom VARCHAR(25),
    qty NUMERIC(10, 2) NOT NULL,
    purchases_price NUMERIC(10, 2) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    summary_purchases_order_count NUMERIC(10, 2),
    summary_purchases_latest_date DATE,
    summary_purchases_latest_price NUMERIC(10, 2),
    summary_purchases_min_price NUMERIC(10, 2),
    summary_purchases_25_percentile_price NUMERIC(10, 2),
    summary_purchases_avg_price NUMERIC(10, 2),
    summary_purchases_median_price NUMERIC(10, 2),
    summary_purchases_75_percentile_price NUMERIC(10, 2),
    summary_purchases_max_price NUMERIC(10, 2),
    summary_upper_purchases_price_std_limit NUMERIC(10, 2),
    summary_lower_purchases_price_std_limit NUMERIC(10, 2),
    summary_upper_purchases_price_iqr_limit NUMERIC(10, 2),
    summary_lower_purchases_price_iqr_limit NUMERIC(10, 2),
    price_diff_percentage NUMERIC(10, 2),
    purchases_price_alert BOOLEAN,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (doc_date, doc_num, line_num)
);