CREATE TABLE IF NOT EXISTS ft_pdt_summary (
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(100) NOT NULL,
    uom VARCHAR(25),
    summary_sales_latest_date DATE ,
    summary_sales_latest_price NUMERIC(10, 2) ,
    summary_sales_order_count INT ,
    summary_sales_avg_price NUMERIC(10, 2) ,
    summary_sales_min_price NUMERIC(10, 2) ,
    summary_sales_median_price NUMERIC(10, 2) ,
    summary_sales_max_price NUMERIC(10, 2) ,
    summary_sales_25_percentile_price NUMERIC(10, 2) ,
    summary_sales_75_percentile_price NUMERIC(10, 2) ,
    summary_sales_price_std NUMERIC(10, 2),
    summary_upper_sales_price_iqr_limit NUMERIC(10, 2) ,
    summary_upper_sales_price_std_limit NUMERIC(10, 2),
    summary_lower_sales_price_iqr_limit NUMERIC(10, 2) ,
    summary_lower_sales_price_std_limit NUMERIC(10, 2),
    summary_sales_total_qty NUMERIC(10, 2) ,
    summary_sales_avg_qty_per_month NUMERIC(10, 2) ,
    summary_sales_total_value NUMERIC(10, 2) ,
    num_customer NUMERIC(10, 2) ,
    summary_sales_start_date DATE ,
    summary_sales_end_date DATE ,
    summary_purchases_latest_date DATE,
    summary_purchases_latest_price NUMERIC(10, 2),
    summary_purchases_order_count INT,
    summary_purchases_avg_price NUMERIC(10, 2),
    summary_purchases_min_price NUMERIC(10, 2),
    summary_purchases_median_price NUMERIC(10, 2),
    summary_purchases_max_price NUMERIC(10, 2),
    summary_purchases_25_percentile_price NUMERIC(10, 2),
    summary_purchases_75_percentile_price NUMERIC(10, 2),
    summary_purchases_price_std NUMERIC(10, 2),
    summary_upper_purchases_price_iqr_limit NUMERIC(10, 2),
    summary_upper_purchases_price_std_limit NUMERIC(10, 2),
    summary_lower_purchases_price_iqr_limit NUMERIC(10, 2),
    summary_lower_purchases_price_std_limit NUMERIC(10, 2),
    summary_purchases_total_qty NUMERIC(10, 2),
    summary_purchases_avg_qty_per_month NUMERIC(10, 2),
    summary_purchases_total_value NUMERIC(10, 2),
    num_supplier NUMERIC(10, 2),
    summary_purchases_start_date DATE,
    summary_purchases_end_date DATE,
    profit_per_qty NUMERIC(10, 2),
    total_profit NUMERIC(10, 2),
    profit_margin NUMERIC(10, 2),
    base_price NUMERIC(10, 2),
    total_loss NUMERIC(10,2),
    num_loss_orders INT,
    new_pdt_indicator VARCHAR(3),
    activity VARCHAR(8),
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pdt_code)
);