CREATE TABLE IF NOT EXISTS ft_pdt_customer_monthly_pivoted_qty (
    pdt_code VARCHAR(50) NOT NULL,
    pdt_name VARCHAR(255) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_group_name VARCHAR(255) NOT NULL,
    uom VARCHAR(25) NOT NULL,
    current_inv NUMERIC(10, 2) NOT NULL,
    jan NUMERIC(10, 2) NOT NULL,
    feb NUMERIC(10, 2) NOT NULL,
    mar NUMERIC(10, 2) NOT NULL,
    apr NUMERIC(10, 2) NOT NULL,
    may NUMERIC(10, 2) NOT NULL,
    jun NUMERIC(10, 2) NOT NULL,
    jul NUMERIC(10, 2) NOT NULL,
    aug NUMERIC(10, 2) NOT NULL,
    sep NUMERIC(10, 2) NOT NULL,
    oct NUMERIC(10, 2) NOT NULL,
    nov NUMERIC(10, 2) NOT NULL,
    december NUMERIC(10, 2) NOT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pdt_code, customer_group_name, customer_code, uom)
);