CREATE TABLE IF NOT EXISTS ft_sales_ops_report (
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(255) NOT NULL,
    foreign_pdt_name VARCHAR(500),
    processed_pdt_ind VARCHAR(25),
    new_pdt_ind VARCHAR(3),
    pdt_main_category VARCHAR(25),
    base_price NUMERIC(10,2),
    uom VARCHAR(50),
    current_inv_qty NUMERIC(10, 2),
    current_inv_value NUMERIC(10, 2),
    avg_monthly_purchase_qty NUMERIC(10,2),
    avg_monthly_sales_qty NUMERIC(10,2),
    avg_weekly_sales_qty NUMERIC(10,2),
    avg_daily_sales_qty NUMERIC(10,2),
    monthly_sales_qty_to_current_inv_ratio NUMERIC(10,2),
    purchase_data_date_range VARCHAR(100),
    latest_purchase_date DATE,
    latest_purchase_price NUMERIC(10, 2),
    min_purchase_price NUMERIC(10, 2),
    max_purchase_price NUMERIC(10, 2),
    sales_data_date_range VARCHAR(100),
    latest_sales_date DATE,
    latest_sales_price NUMERIC(10, 2),
    min_sales_price NUMERIC(10, 2),
    max_sales_price NUMERIC(10, 2),
    had_sales_last_7_days VARCHAR(8),
    sales_activity_category VARCHAR(25),
    ecommerce_pdt_ind VARCHAR(1),
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pdt_code)
);