CREATE TABLE IF NOT EXISTS ft_sales_orders_alerts (
    doc_date DATE NOT NULL,
    doc_num VARCHAR(50) NOT NULL,
    line_num SMALLINT NOT NULL,
    customer_code VARCHAR(25) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_group_name VARCHAR(255) NOT NULL,
    industry VARCHAR(25) NOT NULL,
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(100) NOT NULL,
    processed_pdt_ind TINYINT(1),
    uom VARCHAR(25),
    price NUMERIC(10, 2) NOT NULL,
    qty NUMERIC(10, 2) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    sales_employee_code SMALLINT NOT NULL,
    sales_employee VARCHAR(100) NOT NULL,
    summary_sales_start_date DATE,
    summary_sales_end_date DATE,
    summary_sales_order_count INT,
    summary_sales_min_price NUMERIC(10, 2),
    summary_sales_25_percentile_price NUMERIC(10, 2),
    summary_sales_avg_price NUMERIC(10, 2),
    summary_sales_median_price NUMERIC(10, 2),
    summary_sales_75_percentile_price NUMERIC(10, 2),
    summary_sales_max_price NUMERIC(10, 2),
    summary_upper_sales_price_iqr_limit NUMERIC(10, 2),
    summary_upper_sales_price_std_limit NUMERIC(10, 2),
    summary_lower_sales_price_iqr_limit NUMERIC(10, 2),
    summary_lower_sales_price_std_limit NUMERIC(10, 2),
    summary_purchases_start_date DATE,
    summary_purchases_end_date DATE,
    summary_purchases_latest_date DATE,
    summary_purchases_latest_price NUMERIC(10, 2),
    summary_purchases_order_count INT,
    summary_purchases_avg_price NUMERIC(10, 2),
    summary_purchases_min_price NUMERIC(10, 2),
    summary_purchases_25_percentile_price NUMERIC(10, 2),
    summary_purchases_median_price NUMERIC(10, 2),
    summary_purchases_75_percentile_price NUMERIC(10, 2),
    summary_purchases_max_price NUMERIC(10, 2),
    base_price NUMERIC(10, 2),
    purchase_price NUMERIC(10, 2),
    sales_price_alert BOOLEAN,
    purchase_price_alert BOOLEAN,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (doc_date, doc_num, line_num)
);