CREATE TABLE IF NOT EXISTS ft_sales_ops_report (
    pdt_code VARCHAR(25) NOT NULL,
    pdt_name VARCHAR(255) NOT NULL,
    uom VARCHAR(50),
    current_inv_qty NUMERIC(10, 2),
    current_inv_value NUMERIC(10, 2),
    avg_purchase_qty_per_month NUMERIC(10,2),
    avg_sales_qty_per_month NUMERIC(10,2),
    avg_monthly_sales_to_inv_ratio NUMERIC(10,2),
    purchases_data_date_range VARCHAR(100),
    latest_purchase_date DATE,
    latest_purchase_price NUMERIC(10, 2),
    purchases_min_price NUMERIC(10, 2),
    purchases_max_price NUMERIC(10, 2),
    sales_data_date_range VARCHAR(100),
    latest_sales_date DATE,
    latest_sales_price NUMERIC(10, 2),
    sales_min_price NUMERIC(10, 2),
    sales_max_price NUMERIC(10, 2),
    new_pdt_ind VARCHAR(3),
    activity VARCHAR(8),
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pdt_code)
);